Feature/tags
mikevanl/FireSale pull request #105
Opened 2020-12-17 21:57 UTC by Astrid-HR

2020-12-19 11:55 UTC, JimGeersinga requested changes

2020-12-19 11:55 UTC, JimGeersinga commented on api/src/main/java/com/FireSale/api/dto/auction/AuctionDTO.java
> +    private List<Tag> tags;
Diet moet een lijst van TagDTO zijn

2020-12-19 11:55 UTC, JimGeersinga commented on api/src/main/java/com/FireSale/api/model/Auction.java
> +    private List<Tag> tags;
Hier ook een lijst vN TagDTO

2020-12-19 11:55 UTC, JimGeersinga commented on client/FireSale/src/app/auctions/models/auctionDTO.ts
> +  tags: TagDto[];
TagDto moet TagDTO zijn

2020-12-19 11:55 UTC, JimGeersinga commented on api/src/main/java/com/FireSale/api/dto/auction/AuctionDTO.java
> +    private List<Tag> tags;
Tags moet een lijst zijn van TagDTO

2020-12-19 11:55 UTC, JimGeersinga commented on api/src/main/java/com/FireSale/api/model/Auction.java
> +    private List<Tag> tags;
Tags moet een lijst zijn van TagDTO

2020-12-19 12:31 UTC, Astrid-HR commented on client/FireSale/src/app/auctions/models/auctionDTO.ts
> +  tags: TagDto[];
Hij heet TagDto. Hoe weet ie dan dit ie TagDTO heet?
![image](https://user-images.githubusercontent.com/38784984/102689446-7972d700-41fe-11eb-93c6-7c2c7f8067cf.png)

2020-12-22 19:24 UTC, JimGeersinga approved these changes

2020-12-22 19:24 UTC, JimGeersinga commented on client/FireSale/src/app/shared/services/tag.service.ts
> +  public put(tagDto: TagDto): Observable<any> {
put renamen naar update voor leesbaarheid

2020-12-22 19:24 UTC, merged