Added days to countown
mikevanl/FireSale pull request #106
Opened 2020-12-18 19:58 UTC by 0548643

2020-12-19 11:46 UTC, JimGeersinga requested changes

2020-12-19 11:46 UTC, JimGeersinga commented on client/FireSale/src/app/shared/util.ts
> +    return `${Util.pad(days,1)}d ${Util.pad(hours,1)}:${Util.pad(minutes,2)}:${Util.pad(seconds,2)}`;
Pad voor hours moet 2 zijn

2020-12-19 11:52 UTC, 0548643 commented on client/FireSale/src/app/shared/util.ts
> +    return `${Util.pad(days,1)}d ${Util.pad(hours,1)}:${Util.pad(minutes,2)}:${Util.pad(seconds,2)}`;
1 staat mooier

2020-12-30 20:06 UTC, JimGeersinga approved these changes

2020-12-30 20:06 UTC, merged