Feature/active auctions by user overview front end
mikevanl/FireSale pull request #112
Opened 2021-01-03 19:21 UTC by carloligthart

2021-01-03 19:40 UTC, JimGeersinga requested changes

2021-01-03 19:40 UTC, JimGeersinga commented on api/src/main/java/com/FireSale/api/controller/AuctionController.java
> +            final Collection<Auction> auctions = auctionService.getAuctions();
Tab is niet correct

2021-01-03 19:40 UTC, JimGeersinga commented on api/src/main/java/com/FireSale/api/controller/AuctionController.java
> -
hier hoort een enter

2021-01-03 19:40 UTC, JimGeersinga commented on api/src/main/java/com/FireSale/api/service/AuctionService.java
> +                .filter(a ->  "Ready".equals(a.getStatus().name())).collect(Collectors.toList());
dit wil je in sql doen, je moet niet alleen kijken naar de status, maar ook de remaining time

2021-01-06 12:18 UTC, mikevanl approved these changes

2021-01-06 12:21 UTC, JimGeersinga approved these changes

2021-01-06 12:21 UTC, merged