0548643/auction edit
mikevanl/FireSale pull request #125
Opened 2021-01-10 10:00 UTC by 0548643

You can now edit an auction 🥳

2021-01-10 20:01 UTC, JimGeersinga requested changes

2021-01-10 20:01 UTC, JimGeersinga commented on client/FireSale/src/app/pages/auction-edit/auction-edit.component.ts
> +        if (String(element).startsWith('http://localhost:8080')) {
hardcoded urls is nooit goed

2021-01-10 21:08 UTC, 0548643 commented on api/src/main/java/com/FireSale/api/service/AuctionService.java
> +        if (existing.getStartDate().isBefore(LocalDateTime.now())) throw new UnAuthorizedException("Cannot change a running auction");
Eens, nog niet aan toegekomen maar was ik ook van plan

2021-01-10 21:09 UTC, 0548643 commented on api/src/main/java/com/FireSale/api/service/AuctionService.java
> +            var t = tagService.getTagByName(tag.getName());
O bij de post werkt het ook zo, vandaar dat ik er niet verder over heb nagedacht. Ik zal er beter naar kijken

2021-01-10 21:12 UTC, 0548643 commented on client/FireSale/src/app/app-routing.module.ts
> +  { path: 'auctions/:id/edit', component: AuctionEditComponent, canActivate: [AuthGuard]  },
Eens. Maar bij jouw rewrite van heel de mapstructuur heb jij "edit" geïntroduceerd voor het maken van een nieuwe veiling, dus dit is dan meer kritiek op je eigen werk. Maar ondanks dat zal ik het meenemen.

2021-01-10 21:12 UTC, 0548643 commented on client/FireSale/src/app/pages/auction-edit/auction-edit.component.html
> +        [disabled]="!auctionEditForm.valid || (edit && auctionIsRunning)">{{this.submitbuttontext}}</button>
Niet als ie al loopt inderdaad. Goed gezien.

2021-01-10 21:13 UTC, 0548643 commented on client/FireSale/src/app/pages/auction-edit/auction-edit.component.ts
> +  selectedCategories: number[];
Oei dat weet ik zo even niet. Ga ik naar kijken.

2021-01-10 21:13 UTC, 0548643 commented on client/FireSale/src/app/pages/auction-edit/auction-edit.component.ts
> +    this.currentTags = auction?.tags.map((x) => x.name);
Kan zijn. Ga ik naar kijken.

2021-01-10 21:13 UTC, 0548643 commented on client/FireSale/src/app/pages/auction-edit/auction-edit.component.ts
> +      this.currentTags.map((tag) => {
Mogelijk. Ik ga ernaar kijken.

2021-01-10 21:14 UTC, 0548643 commented on client/FireSale/src/app/pages/auction-edit/auction-edit.component.ts
> +        if (String(element).startsWith('http://localhost:8080')) {
Oké daar kan ik inkomen. Voor nu werkt het wel in ieder geval. Heb jij een suggestie voor een betere check?

2021-01-16 14:02 UTC, mikevanl approved these changes

2021-01-16 18:21 UTC, JimGeersinga approved these changes

2021-01-16 18:21 UTC, merged