Feature/annuleren veiling
mikevanl/FireSale pull request #126
Opened 2021-01-10 13:53 UTC by Astrid-HR

2021-01-10 20:12 UTC, JimGeersinga requested changes

2021-01-10 20:12 UTC, JimGeersinga commented on .gitignore
> +client/FireSale/.vscode/launch.json
deze niet toevoegen

2021-01-10 20:12 UTC, JimGeersinga commented on api/src/main/java/com/FireSale/api/service/AuctionService.java
> +        if (!Guard.isSelf(existing.getUser().getId()) || !Guard.isAdmin()) {
Dit gaat fout als de gebruiker geen admin is, maar wel de eigenaar van zijn eigen veiling, dit moet dus een 'and' zijn

2021-01-10 20:12 UTC, JimGeersinga commented on client/FireSale/src/app/pages/auction-detail/auction-detail.component.html
> +        <button (click)="cancelAuction(model.data)" mat-raised-button color="accent" [disabled]="disableCancelButton$ | async"><b>ANNULEER</b></button>
een button hoort niet in een chip-list

2021-01-10 20:12 UTC, JimGeersinga commented on client/FireSale/src/app/shared/services/auction.service.ts
> +  public currentAuction$: BehaviorSubject<AuctionDTO | null> = new BehaviorSubject(null);
wat is dit?

2021-01-10 20:12 UTC, JimGeersinga commented on client/FireSale/src/app/shared/services/auction.service.ts
> +    const currentAuction = JSON.parse(localStorage.getItem('currentAuction'));
dit hoort hier niet

2021-01-10 20:12 UTC, JimGeersinga commented on client/FireSale/src/app/pages/auction-detail/auction-detail.component.ts
> +    this.route.params.subscribe(params => {
wat moet dit allemaal doen?

2021-01-11 07:32 UTC, Astrid-HR commented on .gitignore
> +client/FireSale/.vscode/launch.json
Dat weet ik, daarom had ik hem ook aan de gitignore toegevoegd. Blijkbaar werkt dat niet zo.

2021-01-11 07:35 UTC, Astrid-HR commented on .gitignore
> +client/FireSale/.vscode/launch.json
ZO te zien heb jij hem al verwijderd, dus deze is resolved

2021-01-11 07:37 UTC, Astrid-HR commented on api/src/main/java/com/FireSale/api/service/AuctionService.java
> +        if (!Guard.isSelf(existing.getUser().getId()) || !Guard.isAdmin()) {
Gewijzigd

2021-01-11 07:47 UTC, Astrid-HR commented on client/FireSale/src/app/pages/auction-detail/auction-detail.component.html
> +        <button (click)="cancelAuction(model.data)" mat-raised-button color="accent" [disabled]="disableCancelButton$ | async"><b>ANNULEER</b></button>
Opgelost

2021-01-11 07:59 UTC, Astrid-HR commented on client/FireSale/src/app/shared/services/auction.service.ts
> +  public currentAuction$: BehaviorSubject<AuctionDTO | null> = new BehaviorSubject(null);
Dat was een van mijn tientallen probeersels. Vergeten te verwijderen. Is nu weg.

2021-01-11 07:59 UTC, Astrid-HR commented on client/FireSale/src/app/shared/services/auction.service.ts
> +    const currentAuction = JSON.parse(localStorage.getItem('currentAuction'));
Zie vorige

2021-01-11 08:02 UTC, Astrid-HR commented on client/FireSale/src/app/pages/auction-detail/auction-detail.component.ts
> +    this.route.params.subscribe(params => {
Feature #117 en #118

2021-01-11 09:07 UTC, mikevanl commented on client/FireSale/src/app/pages/auction-detail/auction-detail.component.html
> +        <button (click)="cancelAuction(model.data)" mat-raised-button color="accent" [disabled]="disableCancelButton$ | async"><b>ANNULEER</b></button>
Lijkt hier alsof de button nogsteeds in de mat-chip-list zit?

2021-01-11 09:07 UTC, mikevanl commented on client/FireSale/src/app/pages/auction-detail/auction-detail.component.ts
> +    this.route.params.subscribe(params => {
Er staan nog een aantal console logs in die sowieso overbodig zijn

2021-01-11 09:12 UTC, mikevanl approved these changes

2021-01-11 09:12 UTC, JimGeersinga approved these changes

2021-01-11 09:13 UTC, merged