Fix/hoogstebod ipv minimumbod
mikevanl/FireSale pull request #147
Opened 2021-01-13 14:47 UTC by Astrid-HR

2021-01-13 15:07 UTC, mikevanl requested changes

2021-01-13 15:07 UTC, mikevanl commented on client/FireSale/src/app/components/auctions/auction-list-item/auction-list-item.component.ts
>          this.latestBid = message.data.value;
Wordt dit nu nog gebruikt? want ik vermoed dat als er een nieuw bod komt het getal niet meer update

2021-01-13 15:07 UTC, mikevanl commented on client/FireSale/src/app/components/auctions/auction-list-item/auction-list-item.component.ts
> +      this.allBids = response.data;
is het nodig deze bids hierna nog op te slaan? dit gebeurd immers maar 1 keer

2021-01-13 15:07 UTC, mikevanl commented on client/FireSale/src/app/components/auctions/auction-list-item/auction-list-item.component.ts
> +      const highest = this.allBids[this.allBids.length - 1];
Geeft dit geen index out of range als er nog geen biedingen zijn?

2021-01-13 15:07 UTC, mikevanl commented on client/FireSale/src/app/components/auctions/auction-list-item/auction-list-item.component.ts
> +      this.highestBid = highest?.value;
kan dit niet iets worden als 
`this.latestBidOnItem = highest?.value ?? this.model.minimalBid || 0;`?

2021-01-13 15:11 UTC, JimGeersinga commented on client/FireSale/src/app/components/auctions/auction-list-item/auction-list-item.component.ts
> +      this.allBids = response.data;
Dit kan ook voor een veel tragere applicatie zorgen. omdat voor alle auctions alle biedingen moeten worden opgehaald.

2021-01-13 15:12 UTC, Astrid-HR commented on client/FireSale/src/app/components/auctions/auction-list-item/auction-list-item.component.ts
>          this.latestBid = message.data.value;
Ja, getHighestBid is in gebruik. Als ik ga bieden en ik ga terug naar de pagina, dan zie ik mijn nieuwe bod op de card.

2021-01-13 15:12 UTC, mikevanl commented on client/FireSale/src/app/components/auctions/auction-list-item/auction-list-item.component.ts
> +      this.allBids = response.data;
Zeker waar. Wellicht beter om te zorgen dat dit al ingeladen wordt bij het ophalen van de lijst

2021-01-13 15:13 UTC, Astrid-HR commented on client/FireSale/src/app/components/auctions/auction-list-item/auction-list-item.component.ts
> +      this.allBids = response.data;
Hij doet dit alleen voor de auctions die cards hebben toch? Niet voor alle?

2021-01-13 15:14 UTC, mikevanl commented on client/FireSale/src/app/components/auctions/auction-list-item/auction-list-item.component.ts
>          this.latestBid = message.data.value;
Data snap ik maar dit gaat over de websocket connectie die tussendoor nog een 'latestBid' update. Dit wordt niet getoond.

2021-01-13 15:14 UTC, Astrid-HR commented on client/FireSale/src/app/components/auctions/auction-list-item/auction-list-item.component.ts
> +      const highest = this.allBids[this.allBids.length - 1];
Ik heb die niet gehad

2021-01-13 15:14 UTC, Astrid-HR commented on client/FireSale/src/app/components/auctions/auction-list-item/auction-list-item.component.ts
> +      this.highestBid = highest?.value;
Die had ik in eerste instantie, maar die wilde niet werken bij mij

2021-01-13 15:15 UTC, mikevanl commented on client/FireSale/src/app/components/auctions/auction-list-item/auction-list-item.component.ts
> +      const highest = this.allBids[this.allBids.length - 1];
@JimGeersinga geeft een index van -1 (bij een lege lijst) geen foutmelding in typescript? (kan zijn dat ik het mis heb)

2021-01-13 15:16 UTC, mikevanl commented on client/FireSale/src/app/components/auctions/auction-list-item/auction-list-item.component.ts
> +      this.allBids = response.data;
Alle auctions worden toch in een card geladen op de homepage?

2021-01-13 15:23 UTC, Astrid-HR commented on client/FireSale/src/app/components/auctions/auction-list-item/auction-list-item.component.ts
>          this.latestBid = message.data.value;
Oh die websocket. Daar maak ik geen gebruik van. Die stond er al en die wilde ik niet verwijderen omdat dat niet mijn code is.

2021-01-13 15:24 UTC, Astrid-HR commented on client/FireSale/src/app/components/auctions/auction-list-item/auction-list-item.component.ts
> +      this.allBids = response.data;
Alleen de actieve toch? Daarom staan er nu ook zo weinig

2021-01-13 15:40 UTC, mikevanl commented on client/FireSale/src/app/components/auctions/auction-list-item/auction-list-item.component.ts
>          this.latestBid = message.data.value;
Dat moet ook zeker niet maar die geeft jou steeds een nieuw bod door, maar die waarde toon je nu niet meer omdat je een nieuwe variabele hebt gemaakt voor het hoogste bod.

2021-01-13 15:42 UTC, mikevanl commented on client/FireSale/src/app/components/auctions/auction-list-item/auction-list-item.component.ts
> +      this.allBids = response.data;
maar stel dat het er zometeen 100 zijn. Dan vuurt iedere gebruiker die die pagina laad 101 verzoeken naar de server.
1 om de auctions op te halen en dan vervolgens per auction die hij binnen krijgt nog een verzoek om alle biedingen op te halen. terwijl als je de biedingen al meegeeft vanaf de server naar de auction list dan scheelt dat per gebruiker 100 verzoeken.

2021-01-13 15:50 UTC, Astrid-HR commented on client/FireSale/src/app/components/auctions/auction-list-item/auction-list-item.component.ts
> +      this.allBids = response.data;
Wat je bedoelt te zeggen is dat deze code eigenlijk op de auction list zou moeten staan en niet op de auction list item?

2021-01-13 15:51 UTC, Astrid-HR commented on client/FireSale/src/app/components/auctions/auction-list-item/auction-list-item.component.ts
>          this.latestBid = message.data.value;
Als die websocket had gewerkt, dan had dit issue er niet geweest, toch?

2021-01-13 15:51 UTC, mikevanl commented on client/FireSale/src/app/components/auctions/auction-list-item/auction-list-item.component.ts
> +      this.allBids = response.data;
nee wat ik wil zeggen is dat als jij /api/auctions/active aanroept deze ook de bids bij de auctions moet geven ipv dat de client die nog apart op moet halen

2021-01-14 07:58 UTC, Astrid-HR commented on client/FireSale/src/app/components/auctions/auction-list-item/auction-list-item.component.ts
> +      this.allBids = response.data;
Ik snap je punt. Is dit for future reference of moet ik opnieuw beginnen met dit item?

2021-01-14 08:19 UTC, mikevanl commented on client/FireSale/src/app/components/auctions/auction-list-item/auction-list-item.component.ts
> +      this.allBids = response.data;
Ik ben van mening dat dit hoort bij deze feature, zeker gezien we nog maar minimaal de tijd hebben voor het oplossen van technical debt.

2021-01-14 08:43 UTC, Astrid-HR commented on client/FireSale/src/app/components/auctions/auction-list-item/auction-list-item.component.ts
> +      this.allBids = response.data;
Ok, ik begin opnieuw. Denk dat we het dan wel even moeten hebben over mijn andere item. Dat jullie daarbij vooraf zeggen hoe het opgelost moet worden, zodat we niet nogmaals in deze situatie belanden

2021-01-16 14:00 UTC, Astrid-HR commented
Heropend ivm nieuwe aanvliegroute

2021-01-16 14:04 UTC, mikevanl approved these changes

2021-01-16 17:46 UTC, merged