Forgot password
mikevanl/FireSale pull request #149
Opened 2021-01-15 12:01 UTC by 0548643

### Forgot password
Na het mergen van deze pr is het op het inlogscherm mogelijk om op "wachtwoord vergeten" te klikken. Je komt dan op een scherm waar je je e-mailadres moet invullen. Om te zorgen dat kwaadwillenden hiermee niet kunnen ontdekken of een e-mailadres wel of niet bekend is verschijnt altijd dezelfde melding, namelijk dat er een wachtwoordresetlink is gestuurd als het adres bestaat.

Het verzenden van de e-mail gaat via instellingen die niet in de code en niet in deze pr zittten. Je moet deze instellingen zelf even aanmaken: maak de file "C:\tmp\firesalemail.properties" aan met de volgende inhoud (de gegevens hier werken niet maar zijn een voorbeeld):
`mail.smtpserver=smtp.gmail.com`
`mail.username=firesaleadmin@gmail.com`
`mail.password=welkom123`
`mail.from=FireSale <firesaleadmin@gmail.com>`

In de mail die je krijgt zit een link met een uniek token. Wanneer je op de link klikt krijg je de mogelijkheid een nieuw wachtwoord in te voeren. Met het submitten van het nieuwe wachtwoord wordt het token meegestuurd. Als het token niet klopt of niet bestaat zal er niets gebeuren. Als het allemaal goed gaat krijg je een melding dat het is gelukt. Op de achtergrond wordt het token meteen verwijderd.

2021-01-15 13:28 UTC, JimGeersinga requested changes

2021-01-15 13:28 UTC, JimGeersinga commented on api/src/main/java/com/FireSale/api/controller/UserSecurityController.java
> +    @Autowired
@autoWired wordt ten strengste afgeraden door Dion en Geoffrey

2021-01-15 13:28 UTC, JimGeersinga commented on api/src/main/java/com/FireSale/api/controller/UserSecurityController.java
> +public class UserSecurityController {
Waarom is er gekozen voor een nieuwe controller?

2021-01-15 13:28 UTC, JimGeersinga commented on api/src/main/java/com/FireSale/api/controller/UserSecurityController.java
> +        final String body = "Gebruik de volgende link om uw wachtwoord te resetten: http://localhost:4200/users/changepassword/" + token;
Zou je van de body een html body kunnen maken, zodat je de link klikbaar kunt maken?

2021-01-15 13:28 UTC, JimGeersinga commented on api/src/main/java/com/FireSale/api/controller/UserSecurityController.java
> +    public SimpleMailMessage constructEmail(User user, String subject, String body) {
Tip: Dit zou ik een aparte bean/util class kunnen

2021-01-15 13:28 UTC, JimGeersinga commented on api/src/main/java/com/FireSale/api/dto/usersecurity/ChangepasswordDTO.java
> +    private String token;
Zou je deze gelijk kunnen valideren op Type = GUID?

2021-01-15 13:28 UTC, JimGeersinga commented on api/src/main/java/com/FireSale/api/dto/usersecurity/ChangepasswordDTO.java
> +    private String password;
Gebruik ook gelijk validatie annotaties, zoals @NotEmpty en de pattern validatie

2021-01-15 13:28 UTC, JimGeersinga commented on api/src/main/java/com/FireSale/api/dto/usersecurity/EmailadressDTO.java
> +public class EmailadressDTO {
address is met twee D's

2021-01-15 13:28 UTC, JimGeersinga commented on api/src/main/java/com/FireSale/api/model/PasswordResetToken.java
> +    @Id
Maak gebruik van de BaseEntity

2021-01-15 13:28 UTC, JimGeersinga commented on api/src/main/java/com/FireSale/api/model/PasswordResetToken.java
> +    private String token;
Je kunt deze als unique identifier opslaan in de database

2021-01-15 13:28 UTC, JimGeersinga commented on api/src/main/java/com/FireSale/api/repository/PasswordResetTokenRepository.java
> +    @Query("delete from PasswordResetToken t where t.expiryDate <= ?1")
Ik zou dit alleen doen voor de huidige user

2021-01-15 13:28 UTC, JimGeersinga commented on api/src/main/java/com/FireSale/api/repository/PasswordResetTokenRepository.java
> +    void deleteByExpiryDateLessThan(Date now);
Ik zou dit alleen doen voor de huidige user

2021-01-15 13:28 UTC, JimGeersinga commented on api/src/main/java/com/FireSale/api/service/UserSecurityService.java
> +    private boolean isTokenFound(PasswordResetToken passToken) {
TIP: Deze functie is niet heel nuttig. het is net zo makkelijk om pasToken != null te schrijven

2021-01-15 13:28 UTC, JimGeersinga commented on api/src/main/java/com/FireSale/api/service/UserSecurityService.java
> +        return passToken.getExpiryDate().before(cal.getTime());
ik zou hier gewoon localdatetime voor gebruiken

2021-01-15 13:28 UTC, JimGeersinga commented on client/FireSale/src/app/pages/change-password/change-password.component.ts
> +          password: [null],
ik mis een pattern validation

2021-01-15 13:28 UTC, JimGeersinga commented on client/FireSale/src/app/pages/change-password/change-password.component.ts
> +        });
als de gegevens succesvol zijn gewijzigd, na het sluiten van de popup redirecten naar login

2021-01-15 13:28 UTC, JimGeersinga commented on client/FireSale/src/app/pages/change-password/change-password.component.html
> +                resetten</button>
Knop hernoemen naar Wachtwoord opslaan

2021-01-15 13:28 UTC, JimGeersinga commented on client/FireSale/src/app/pages/forgot-password/forgot-password.component.ts
> +      this.forgotpasswordService.post(data).subscribe();
is er getest of deze call wordt aangeroepen

2021-01-15 13:28 UTC, JimGeersinga commented on client/FireSale/src/app/shared/services/forgotpassword.service.ts
> +export class ForgotpasswordService {
maak gebruik van de al bestaande userservice

2021-01-15 13:50 UTC, 0548643 commented on api/src/main/java/com/FireSale/api/controller/UserSecurityController.java
> +public class UserSecurityController {
Ik wilde het voor het gemak gescheiden houden omdat ik niet weet wat jullie van de week allemaal nog in de controllers doen. Op deze manier hebben we sowieso geen mergeconflicts. Ik had het eerst alles in de UserController. Kan ook hoor. Maar als het zo ook mag dan graag, scheelt weer werk nu en straks.

2021-01-15 13:51 UTC, 0548643 commented on api/src/main/java/com/FireSale/api/controller/UserSecurityController.java
> +        final String body = "Gebruik de volgende link om uw wachtwoord te resetten: http://localhost:4200/users/changepassword/" + token;
Ja niet eens aan gedacht. Ik heb getest met mailjes die terecht kwamen in Gmail, Outlook en RoundCube, en al deze mailclients zijn slim genoeg er een link van te maken.

2021-01-15 13:53 UTC, 0548643 commented on api/src/main/java/com/FireSale/api/repository/PasswordResetTokenRepository.java
> +    void deleteByExpiryDateLessThan(Date now);
Maar er is geen huidige user want hij kan niet inloggen, daarom vraagt ie een nieuw wachtwoord op. Of wil je dat ik gewoon het e-mailadres meeneem?

2021-01-15 13:53 UTC, 0548643 commented on api/src/main/java/com/FireSale/api/repository/PasswordResetTokenRepository.java
> +    @Query("delete from PasswordResetToken t where t.expiryDate <= ?1")
Idem

2021-01-15 13:54 UTC, 0548643 commented on client/FireSale/src/app/pages/forgot-password/forgot-password.component.ts
> +      this.forgotpasswordService.post(data).subscribe();
Ja. Twijfel je aan de werking?

2021-01-15 14:03 UTC, JimGeersinga commented on api/src/main/java/com/FireSale/api/controller/UserSecurityController.java
> +public class UserSecurityController {
Mergeconflicts zijn geen problemen die je wilt voorkomen door nieuwe bestanden aan te maken. Dit maakt het slechter onderhoudbaar.
Graag in de usercontroller plaatsen :)

2021-01-15 14:04 UTC, JimGeersinga commented on api/src/main/java/com/FireSale/api/repository/PasswordResetTokenRepository.java
> +    void deleteByExpiryDateLessThan(Date now);
nee, laat maar even voor wat het is

2021-01-15 14:04 UTC, JimGeersinga commented on api/src/main/java/com/FireSale/api/repository/PasswordResetTokenRepository.java
> +    @Query("delete from PasswordResetToken t where t.expiryDate <= ?1")
laat maar even voor wat het is

2021-01-15 14:09 UTC, 0548643 commented on api/src/main/java/com/FireSale/api/controller/UserSecurityController.java
> +        final String body = "Gebruik de volgende link om uw wachtwoord te resetten: http://localhost:4200/users/changepassword/" + token;
Done

2021-01-15 14:26 UTC, 0548643 commented on api/src/main/java/com/FireSale/api/dto/usersecurity/EmailadressDTO.java
> +public class EmailadressDTO {
O ja dat is in het Engels anders dan in het Nederlands

2021-01-15 14:31 UTC, 0548643 commented on api/src/main/java/com/FireSale/api/service/UserSecurityService.java
> +    private boolean isTokenFound(PasswordResetToken passToken) {
Dit maakt het wel beter leesbaar

2021-01-15 14:32 UTC, 0548643 commented on api/src/main/java/com/FireSale/api/service/UserSecurityService.java
> +        return passToken.getExpiryDate().before(cal.getTime());
Heb je een linkje met een voorbeeld? We zijn hier zelf ook al even mee bezig geweest en waren al blij dat dit werkte.

2021-01-15 15:11 UTC, 0548643 commented on api/src/main/java/com/FireSale/api/controller/UserSecurityController.java
> +        final String body = "Gebruik de volgende link om uw wachtwoord te resetten: http://localhost:4200/users/changepassword/" + token;
En weer teruggedraaid, als ik er domweg `<a href="... etc.` in zet dan komt dat als plain text in de body, waar dan de mailclient weer iets intelligents mee gaat doen en dat werkt dan helemaal niet meer. En ik vind het zonde van mijn tijd om uit te gaan zoeken hoe ik een deftig HTML mailtje maak. Als we bij de presentatie en demo gewoon een zichzelfrespecterende client gebruiken is er niets aan de hand.

2021-01-15 15:33 UTC, 0548643 commented on client/FireSale/src/app/shared/services/forgotpassword.service.ts
> +export class ForgotpasswordService {
Heb ik ook expres apart gezet om mergeconflicts te voorkomen, maar bij dezen zijn ze samengevoegd

2021-01-15 15:34 UTC, JimGeersinga commented on client/FireSale/src/app/pages/forgot-password/forgot-password.component.ts
> +      this.forgotpasswordService.post(data).subscribe();
Ik weet niet zeker of een subscribe call zonder action zou werken.

2021-01-15 15:37 UTC, 0548643 commented on api/src/main/java/com/FireSale/api/controller/UserSecurityController.java
> +public class UserSecurityController {
Check

2021-01-15 15:43 UTC, JimGeersinga requested changes

2021-01-15 15:43 UTC, JimGeersinga commented on api/src/main/java/com/FireSale/api/dto/usersecurity/ChangepasswordDTO.java
> +    private UUID token;
Is hier nog een @NotEmpty voor nodig?

2021-01-15 15:43 UTC, JimGeersinga commented on api/src/main/java/com/FireSale/api/dto/usersecurity/EmailaddressDTO.java
> +    private String emailaddress;
Hier ook gelijk validatie op?

2021-01-15 15:43 UTC, JimGeersinga commented on api/src/main/java/com/FireSale/api/model/PasswordResetToken.java
> +    @Id
Nu de  baseentity gebruikt wordt is de id in passwordresettoken niet meer nodig

2021-01-15 15:43 UTC, JimGeersinga commented on api/src/main/java/com/FireSale/api/model/PasswordResetToken.java
> +    private String token;
met unique bedoel ik niet perse de unique constraint, maar meer het type

2021-01-15 15:43 UTC, JimGeersinga commented on api/src/main/java/com/FireSale/api/service/UserSecurityService.java
> +    private boolean isTokenFound(PasswordResetToken passToken) {
depends. voor mij is dit meer regels code die ik moet doorlezen

2021-01-15 15:43 UTC, JimGeersinga commented on api/src/main/java/com/FireSale/api/service/UserSecurityService.java
> +        return passToken.getExpiryDate().before(cal.getTime());
kun je LocalDateTime. now() gebruiken?

2021-01-15 15:43 UTC, JimGeersinga commented on client/FireSale/src/app/pages/forgot-password/forgot-password.component.ts
> +    emailaddress: ['', Validators.required],
hier moet nog een email validator op

2021-01-15 15:43 UTC, JimGeersinga commented on client/FireSale/src/app/shared/services/user.service.ts
> +  public post(emailaddress: EmailaddressDto): Observable<any> {
zou je deze functie willen hernoemen naar requestPassword of iets dergelijks

2021-01-15 15:43 UTC, JimGeersinga commented on client/FireSale/src/app/shared/services/user.service.ts
> +  public update(newPasswordAndToken: ChangepasswordDto): Observable<any> {
zou je deze functie willen hernoemen naar changePassword of iets dergelijks

2021-01-15 15:47 UTC, 0548643 commented on api/src/main/java/com/FireSale/api/dto/usersecurity/ChangepasswordDTO.java
> +    private UUID token;
Als ik het goed heb betekend `{8,}` in het pattern dat het ten minste 8 tekens moet zijn. Ik haal hem weg.

2021-01-15 15:50 UTC, 0548643 commented on api/src/main/java/com/FireSale/api/service/UserSecurityService.java
> +    private boolean isTokenFound(PasswordResetToken passToken) {
Haha ja zo kan je het ook zien. Ik zal eens over nadenken :)

2021-01-15 15:52 UTC, 0548643 commented on api/src/main/java/com/FireSale/api/service/UserSecurityService.java
> +        return passToken.getExpiryDate().before(cal.getTime());
![image](https://user-images.githubusercontent.com/47535630/104748422-06537680-5752-11eb-84a7-28207f1fea4c.png)
Nee

2021-01-15 20:39 UTC, 0548643 commented on client/FireSale/src/app/pages/forgot-password/forgot-password.component.ts
> +      this.forgotpasswordService.post(data).subscribe();
Kennelijk wel want het werkt

2021-01-15 20:40 UTC, 0548643 commented on api/src/main/java/com/FireSale/api/service/UserSecurityService.java
> +        return passToken.getExpiryDate().before(cal.getTime());
Ik vind het mooi zo

2021-01-16 12:12 UTC, JimGeersinga requested changes

2021-01-16 12:12 UTC, JimGeersinga commented on api/src/main/java/com/FireSale/api/controller/UserController.java
> +        final String body = "Gebruik de volgende link om uw wachtwoord te resetten: http://localhost:4200/users/changepassword/" + token;
hier nog een link van maken?
<a href /> ?

2021-01-16 12:12 UTC, JimGeersinga commented on api/src/main/java/com/FireSale/api/dto/usersecurity/ChangepasswordDTO.java
> +    private UUID token;
Zo bedoelde ik hem niet. Je hebt bij allebij de velden '@NotEmpty' nodig :)

2021-01-16 12:12 UTC, JimGeersinga commented on api/src/main/java/com/FireSale/api/model/PasswordResetToken.java
> +    private Date expiryDate;
hier LocalDate van maken of LocalDateTime

2021-01-16 12:12 UTC, JimGeersinga commented on api/src/main/java/com/FireSale/api/service/UserSecurityService.java
> +        return passToken.getExpiryDate().before(cal.getTime());
LocalDate wordt aangeraden door Dion en Geoffrey

2021-01-16 22:36 UTC, JimGeersinga requested changes

2021-01-16 22:36 UTC, JimGeersinga commented on api/src/main/java/com/FireSale/api/service/UserSecurityService.java
>          final Calendar cal = Calendar.getInstance();
calendar wordt niet meer gebruikt, dus die kan weg

2021-01-18 10:42 UTC, JimGeersinga approved these changes

2021-01-18 10:42 UTC, merged