Mark auction as featured
mikevanl/FireSale pull request #150
Opened 2021-01-16 10:12 UTC by Astrid-HR

2021-01-16 12:04 UTC, JimGeersinga requested changes

2021-01-16 12:04 UTC, JimGeersinga commented on client/FireSale/src/app/pages/auction-detail/auction-detail.component.html
> +      <button (click)="markAsFeatured(model.data)" mat-raised-button color="accent"
Als de button disabled is kun je er niet op klikken toch?

2021-01-16 12:04 UTC, JimGeersinga commented on client/FireSale/src/app/pages/auction-detail/auction-detail.component.ts
> +    this.currentUser$ = this.userService.currentUser$;
wanneer je currentuser$ niet elders gebruikt hoef je het niet naar een publieke property te zetten dus zou dit voldoende zijn:
this.userService.currentUser$.subscribe(item => {
      this.isAdmin = item && item.role === 'ADMIN';
    });

2021-01-16 12:06 UTC, JimGeersinga requested changes

2021-01-16 12:06 UTC, JimGeersinga commented on client/FireSale/src/app/pages/auction-detail/auction-detail.component.ts
> +  markAsFeatured(data: CreateAuctionDTO): void {
eigenlijk  wil je niet het hele model als data mee krijgen. je wilt alleen de featured property zetten

2021-01-16 13:30 UTC, Astrid-HR commented on client/FireSale/src/app/pages/auction-detail/auction-detail.component.html
> +      <button (click)="markAsFeatured(model.data)" mat-raised-button color="accent"
Dat klopt. Dat wil je ook niet als de auction al featured is.

2021-01-16 13:38 UTC, Astrid-HR commented on client/FireSale/src/app/pages/auction-detail/auction-detail.component.ts
> +    this.currentUser$ = this.userService.currentUser$;
Done

2021-01-16 13:39 UTC, Astrid-HR commented on client/FireSale/src/app/pages/auction-detail/auction-detail.component.ts
> +  markAsFeatured(data: CreateAuctionDTO): void {
De patch verwacht een volledige auction. Zelfde als bij annuleren.

2021-01-16 18:00 UTC, JimGeersinga commented on client/FireSale/src/app/pages/auction-detail/auction-detail.component.ts
> +  markAsFeatured(data: CreateAuctionDTO): void {
De patch verwacht een object waarbij 1 van de mogelijke properties gevuld is. De put verwacht een volledig gevuld object.
Het zou nu dus kunnen voorkomen dat er properties worden overschreven terwijl dat niet de bedoeling is.
Bij het annuleren is het eigenlijk precies hetzelfde.

Ik zal dit zelf wel aanpassen, want het hoort eigenlijk niet.

2021-01-16 18:05 UTC, JimGeersinga requested changes

2021-01-16 18:05 UTC, JimGeersinga commented on client/FireSale/src/app/pages/auction-detail/auction-detail.component.html
> +      <button (click)="markAsFeatured(model.data)" mat-raised-button color="accent"
Maar hoe kan een admin een featured auction verwijderen dan?

2021-01-16 18:05 UTC, JimGeersinga commented on client/FireSale/src/app/pages/auction-detail/auction-detail.component.ts
> +  public currentUser$: Observable<UserDto>;
als properties niet meer gebruikt worden, dan ook graag verwijderen

2021-01-17 10:38 UTC, Astrid-HR commented on client/FireSale/src/app/pages/auction-detail/auction-detail.component.html
> +      <button (click)="markAsFeatured(model.data)" mat-raised-button color="accent"
Niet via de voorkant. Dat hoefde namelijk niet van Dion.

2021-01-17 10:43 UTC, Astrid-HR commented on client/FireSale/src/app/pages/auction-detail/auction-detail.component.ts
> +  public currentUser$: Observable<UserDto>;
Done

2021-01-17 10:54 UTC, JimGeersinga approved these changes

2021-01-17 11:22 UTC, merged