Feature/ui new auction
mikevanl/FireSale pull request #73
Opened 2020-11-30 18:47 UTC by Astrid-HR

2020-11-30 19:37 UTC, JimGeersinga commented
Misschien handig, om ook de startdatum, einddatum en minimum prijs etc in te kunnen vullen?

2020-11-30 19:44 UTC, JimGeersinga requested changes
Missende velden moeten nog worden toegevoegd:
- Start datum
- Eind datum
- etc...

2020-12-02 11:34 UTC, Astrid-HR commented
> Misschien handig, om ook de startdatum, einddatum en minimum prijs etc in te kunnen vullen?

Done

2020-12-02 11:45 UTC, JimGeersinga requested changes

2020-12-02 11:45 UTC, JimGeersinga commented on client/FireSale/src/app/auctions/components/new-auction/new-auction.component.scss
> +mat-form-field {
d.m.v. fullWidth attribute is dit niet nodig

2020-12-02 11:45 UTC, JimGeersinga commented on client/FireSale/src/app/auctions/models/auctionDto.ts
> +}
Mist allerlei velden

2020-12-02 11:55 UTC, Astrid-HR commented on client/FireSale/src/app/auctions/models/auctionDto.ts
> +}
Comments verwerkt. Excuus, ik had de Dto vergeten.

2020-12-02 12:09 UTC, JimGeersinga approved these changes

2020-12-02 12:10 UTC, merged