Feature/layout
mikevanl/FireSale pull request #75
Opened 2020-12-06 11:35 UTC by mikevanl

2020-12-06 11:36 UTC, mikevanl commented
Travis zal fout status aangeven doordat er een branch in deze is gemerged die 'kapot' gaat

2020-12-06 22:53 UTC, JimGeersinga requested changes

2020-12-06 22:53 UTC, JimGeersinga commented on client/.vs/ProjectSettings.json
> +{
graag .vs directory toevoegen aan .gitignore

2020-12-06 22:53 UTC, JimGeersinga commented on api/src/test/java/com/FireSale/api/controller/UserControllerTests.java
> +    private AuctionController controller;
een auctioncontroller test hoort niet in een usercontroller test

2020-12-06 22:53 UTC, JimGeersinga commented on api/src/main/java/com/FireSale/api/controller/AuctionController.java
> +        try {
try - catch mag weg in de controllers

2020-12-06 22:53 UTC, JimGeersinga commented on api/src/main/java/com/FireSale/api/controller/AuctionController.java
> +    @PreAuthorize("@guard.isSelf(#userId)")
Dit gaat fout #userid bestaat niet

2020-12-06 22:53 UTC, JimGeersinga commented on api/src/main/java/com/FireSale/api/controller/AuctionController.java
> +    @PreAuthorize("@guard.isSelf(#userId)")
Dit gaat fout #userid bestaat niet

2020-12-07 10:24 UTC, JimGeersinga approved these changes

2020-12-07 10:29 UTC, merged